// <auto-generated />
using System;
using EjemploLlaveForanea;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EjemploLlaveForanea.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EjemploLlaveForanea.Entidades.Moneda", b =>
                {
                    b.Property<int>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoneda"));

                    b.Property<string>("NombreMoneda")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("IdMoneda");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("EjemploLlaveForanea.Entidades.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<int?>("MonedaIdMoneda")
                        .HasColumnType("int");

                    b.Property<string>("NombrePais")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdPais");

                    b.HasIndex("MonedaIdMoneda");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("EjemploLlaveForanea.Entidades.Pais", b =>
                {
                    b.HasOne("EjemploLlaveForanea.Entidades.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaIdMoneda");

                    b.Navigation("Moneda");
                });
#pragma warning restore 612, 618
        }
    }
}
